In [1]:
import random
import numpy as np
import pandas as pd


In [2]:
# num_rows = 100
# num_columns = 7203

# # Create an array with integers from 1 to 7203
# base_array = np.arange(1, num_columns + 1)

# # Tile this base array to create a DataFrame with the desired shape
# data_array = np.tile(base_array, (num_rows, 1))

# # Convert the NumPy array to a DataFrame
# df = pd.DataFrame(data_array)

# # Display the DataFrame to check
# print(df.head())
# print(f"DataFrame shape: {df.shape}")

In [3]:
df = pd.read_csv('./data/balanced/train.csv')
# df = pd.read_csv('./data/balanced/test.csv')
columns = df.columns
train = df.iloc[:, :-1]

In [4]:
train.columns

Index(['735', '706', '678', '660', '599', '541', '514', '549', '566', '517',
       ...
       '-16697', '-16254', '-15761', '-15258', '-14772', '-14318', '-13868',
       '-13397', '-12878', '-12361'],
      dtype='object', length=7203)

In [5]:
def split_3_channel(df, split=3):
    num_rows, num_cols = df.shape
    num_parts = num_cols // split
    data = np.zeros((num_rows, split, num_parts))
    for x in range(num_rows):
        a = df.iloc[x, 0:num_parts]
        b = df.iloc[x, num_parts : 2 * num_parts]
        c = df.iloc[x, 2 * num_parts : 3 * num_parts]
        data[x][0] = a
        data[x][1] = b
        data[x][2] = c
    return data

resaped_data = split_3_channel(df=df)

In [6]:
resaped_data[0]

array([[ 37349.,  37391.,  37442., ...,  24456.,  24767.,  25574.],
       [-55429., -55582., -55752., ...,  -1509.,  -2277.,  -2414.],
       [-83904., -84437., -84979., ...,  64403.,  61726.,  59134.]])

In [7]:
train.iloc[0][4802:7203].to_numpy()

array([-83904, -84437, -84979, ...,  64403,  61726,  59134], dtype=int64)

In [8]:
input_data = resaped_data
type(input_data)


numpy.ndarray

In [9]:
input_data

array([[[ 3.7349e+04,  3.7391e+04,  3.7442e+04, ...,  2.4456e+04,
          2.4767e+04,  2.5574e+04],
        [-5.5429e+04, -5.5582e+04, -5.5752e+04, ..., -1.5090e+03,
         -2.2770e+03, -2.4140e+03],
        [-8.3904e+04, -8.4437e+04, -8.4979e+04, ...,  6.4403e+04,
          6.1726e+04,  5.9134e+04]],

       [[-5.3730e+03, -5.3740e+03, -5.4200e+03, ..., -4.8900e+03,
         -4.8960e+03, -4.8610e+03],
        [-6.4920e+03, -6.4360e+03, -6.3590e+03, ..., -6.4560e+03,
         -6.3940e+03, -6.3850e+03],
        [-3.4920e+03, -3.5260e+03, -3.5210e+03, ..., -2.9060e+03,
         -2.7940e+03, -2.7310e+03]],

       [[-3.4150e+03, -3.3930e+03, -3.4050e+03, ..., -2.1000e+02,
         -1.4600e+02, -1.4200e+02],
        [-1.8820e+03, -1.9350e+03, -1.9320e+03, ...,  2.3400e+02,
          1.9600e+02,  1.8500e+02],
        [ 3.8430e+03,  3.8120e+03,  3.7540e+03, ..., -1.1760e+03,
         -1.1340e+03, -1.0980e+03]],

       ...,

       [[-1.2544e+04, -1.2621e+04, -1.2621e+04, ..., -1.3347e+0

In [10]:
type(input_data)
label = df['lables']
label_data = label.to_numpy()
print(type(label_data))

<class 'numpy.ndarray'>


In [11]:
unique_values, count  = np.unique(label_data, return_counts=True)
print((unique_values, count))

(array(['Lg', 'P', 'Pg', 'Pn', 'S', 'Sn'], dtype=object), array([2725, 2694, 2680, 2694, 1185, 2694], dtype=int64))


In [12]:
# # np.save('./data/balanced/input_data.npy', input_data)
# np.save('./data/balanced/test_data.npy', input_data)

# # np.save('./data/balanced/label_data.npy', label_data)
# np.save('./data/balanced/test_label_data.npy', label_data)
