In [1]:
import random
import numpy as np
import pandas as pd


In [2]:
# num_rows = 100
# num_columns = 7203

# # Create an array with integers from 1 to 7203
# base_array = np.arange(1, num_columns + 1)

# # Tile this base array to create a DataFrame with the desired shape
# data_array = np.tile(base_array, (num_rows, 1))

# # Convert the NumPy array to a DataFrame
# df = pd.DataFrame(data_array)

# # Display the DataFrame to check
# print(df.head())
# print(f"DataFrame shape: {df.shape}")

In [3]:
# df = pd.read_csv('./data/balanced/train.csv',nrows=5)
df = pd.read_csv('./data/balanced/test.csv')
columns = df.columns
train = df.iloc[:, :-1]

In [4]:
train.columns

Index(['735', '706', '678', '660', '599', '541', '514', '549', '566', '517',
       ...
       '-16697', '-16254', '-15761', '-15258', '-14772', '-14318', '-13868',
       '-13397', '-12878', '-12361'],
      dtype='object', length=7203)

In [5]:
def split_3_channel(df, split=3):
    num_rows, num_cols = df.shape
    num_parts = num_cols // split
    data = np.zeros((num_rows, split, num_parts))
    for x in range(num_rows):
        a = df.iloc[x, 0:num_parts]
        b = df.iloc[x, num_parts : 2 * num_parts]
        c = df.iloc[x, 2 * num_parts : 3 * num_parts]
        data[x][0] = a
        data[x][1] = b
        data[x][2] = c
    return data

resaped_data = split_3_channel(df=df)

In [6]:
resaped_data[0]

array([[ -2485.,  -2302.,  -2194., ...,   -726.,   -525.,   -282.],
       [-11258., -11273., -11225., ...,  -3451.,  -3884.,  -4405.],
       [  1748.,   1744.,   1861., ...,   2247.,   2049.,   1832.]])

In [7]:
train.iloc[0][4802:7203].to_numpy()

array([1748, 1744, 1861, ..., 2247, 2049, 1832], dtype=int64)

In [8]:
input_data = resaped_data
type(input_data)


numpy.ndarray

In [9]:
input_data

array([[[-2.4850e+03, -2.3020e+03, -2.1940e+03, ..., -7.2600e+02,
         -5.2500e+02, -2.8200e+02],
        [-1.1258e+04, -1.1273e+04, -1.1225e+04, ..., -3.4510e+03,
         -3.8840e+03, -4.4050e+03],
        [ 1.7480e+03,  1.7440e+03,  1.8610e+03, ...,  2.2470e+03,
          2.0490e+03,  1.8320e+03]],

       [[-4.7445e+04, -4.9376e+04, -4.8415e+04, ..., -4.4900e+04,
         -4.4314e+04, -4.5359e+04],
        [-1.2865e+04, -1.2402e+04, -9.1850e+03, ..., -8.0480e+03,
         -7.5350e+03, -8.2750e+03],
        [-1.2842e+04, -1.3145e+04, -1.2911e+04, ..., -1.0136e+04,
         -1.0460e+04, -1.1284e+04]],

       [[ 8.2354e+04,  8.2227e+04,  8.2095e+04, ...,  4.0240e+03,
          3.9570e+03,  3.9050e+03],
        [-2.9107e+04, -2.8902e+04, -2.8649e+04, ..., -3.0082e+04,
         -2.9605e+04, -2.9504e+04],
        [ 1.4401e+04,  1.4403e+04,  1.4402e+04, ...,  1.5091e+04,
          1.5091e+04,  1.5093e+04]],

       ...,

       [[ 4.6600e+02,  1.5720e+03,  2.9500e+02, ...,  3.6520e+0

In [10]:
type(input_data)
label = df['lables']
label_data = label.to_numpy()
print(type(label_data))

<class 'numpy.ndarray'>


In [11]:
np.save('./data/balanced/test_data.npy', input_data)
np.save('./data/balanced/test_label_data.npy', label_data)
